default_twitter: &default_twitter
  twitter_api_key: 'D0wKhEWCJOjYLS1zNw4TCiCup'
  twitter_api_secret: 'oDZUczMOFJNW70qDLAyS6s43pcH3GUDzliwqOYCptXqqnASzFk'


development:
  secret_key_base: 4a1311c78a5999588ec387c12a656f6137aea12eab30cf2410d59034fee2f2d87137e47bd198cb34c5416a3eec84417c33b3b7dc221dc3ebb9b623fbc6d3a98d
  <<: *default_twitter


test:
  secret_key_base: f4cd528b797539db7c9ac06f68fa5f6234c8414de9023a556c91ecf73ff5b7abf6f5193f7f0b3558a5fad8132be9b11d8c3e89d167c17594f50f07571e63f021
  <<: *default_twitter


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
